---
title: "Análise da replicação de Carvalho et al. 2012"
output:
    html_document:
    df_print: paged
    code_folding: hide
theme: sandstone
params: 
    arquivo_dados: "data/wl_fitdist_best.txt"
    arquivo_modelo_carga: "results/wl_fitdist_all.txt"
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(ggbeeswarm)
library(gridExtra)
theme_set(theme_bw())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 7,
                      fig.height = 5)

```

## Análise do arquivo com o modelo de carga de trabalho
arquivo: wl_fitdist_all.txt

Tabela com resultados para a avaliação do modelo proposto

```{r}

dados_modelo_carga <- read_table2(here::here(params$arquivo_modelo_carga), col_names = TRUE)

glimpse(dados_modelo_carga)

```

```{r}
dados_modelo_carga %>%
  ggplot(mapping = aes(y = ratio, x = k, color = distribution )) +
  facet_grid(stats.attr ~ Trace) + 
  geom_line()
```

## Análise do arquivo com o modelo de carga de trabalho
arquivo: wl_fitdist_all.txt

Tabela com resultados para a avaliação do modelo proposto

Os labels foram ajustados

```{r}
dados_modelo_carga_labels = dados_modelo_carga

dados_modelo_carga_labels <- dados_modelo_carga_labels %>%
    mutate(Trace_label = case_when(
      Trace == "gwa-t1" ~ "GS1",
      Trace == "gwa-t2" ~ "GS2",
      Trace == "gwa-t3" ~ "GS3",
      Trace == "gwa-t4" ~ "GS4",
      Trace == "gwa-t10" ~ "GS5",
      Trace == "gwa-t11" ~ "GS6",
      )
    )

dados_modelo_carga_labels <- dados_modelo_carga_labels %>%
    mutate( atributos_carga = case_when(
      stats.attr == "bot_user_iat" ~ "JIST",
      stats.attr == "bot_runtime_sum" ~ "JET",
      stats.attr == "task_runtime" ~ "TET"
      )
    )

glimpse(dados_modelo_carga_labels)
```

```{r}
dados_modelo_carga_labels %>%
  ggplot(mapping = aes(y = ratio, x = k, color = distribution )) +
  facet_grid(atributos_carga ~ Trace_label) + 
  geom_line() +
#  ylab("Group Goodeness-of-Fit (GGoF)") +
  theme(plot.title=element_text(hjust=0.5), text=element_text(size=12)) +
  theme_update(legend.position = "top") +
  labs(
    color = "Distribuição de Probabilidade",
    x = "k (número de clusters)",
    y = "Group Goodeness-of-Fit (GGoF)",
    caption = "Figura 2: Resultados do GGoF para diferentes cenários de ajuste."
  )

ggsave("figura2.png", width=8, height = 5, dpi=600)
```
